# Generated by Django 2.0.5 on 2018-05-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PolledInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimes', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='polledinfo',
            name='name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Voter'),
        ),
        migrations.AddField(
            model_name='polledinfo',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Article'),
        ),
    ]
