# Generated by Django 2.0.5 on 2018-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_auto_20180527_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
